name: Publish Pelican Blog
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          repository: rajbot/bitstream.io
          path: bitstream.io
      - name: Checkout build repo
        uses: actions/checkout@v2
        with:
          repository: rajbot/rajbot.github.io
          path: rajbot.github.io
      - name: Checkout theme repo
        uses: actions/checkout@v2
        with:
          repository: rajbot/bitstream.io_pelican_theme
          path: bitstream.io_pelican_theme
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'
      - name: Install python packages
        run: |
          pip install -r bitstream.io/requirements.txt
      - name: Set pelican theme
        run: |
          pelican-themes --symlink $(pwd)/bitstream.io_pelican_theme
      - name: Generate pelican content
        working-directory: ./bitstream.io
        run: |
          pelican --verbose content/ -s pelicanconf.py
      - name: Push changes
        working-directory: ./rajbot.github.io
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff-index --quiet HEAD || (git add . && git commit -m "generated" && git push)
